Repository highcharts/connectors-morningstar, pull requests merged in 2024-09, with the labels that each got.

#33 Added CLI docs command.
  docs/connectors/morningstar.md
  docs/connectors/morningstar/time-series/time-series.md
  package-build.json
  package-lock.json
  package.json
  src/CLI/Library/Server.ts
  src/CLI/connectors-morningstar.ts
Labels: enhancement

#35 Fixed postman support in CLI server.
  demos/dashboards-rna-news/demo.html
  demos/stock-ohlcv/demo.html
  demos/stock-timeseries/demo.html
  src/CLI/Library/Server.ts
  src/CLI/connectors-morningstar.ts
  src/Shared/MorningstarPostman.ts
Labels: bugfix

#36 Simplified unit-tests.
  .github/workflows/tests.yml
  package.json
  tests/README.md
  tests/RNANews/RNANewsConverter.test.ts
  tests/Shared/MorningstarAPI.test.ts
  tests/TimeSeries/CumulativeReturn.test.ts
  tests/TimeSeries/DividendConverter.test.ts
  tests/TimeSeries/Growth.test.ts
  tests/TimeSeries/OHLCV.test.ts
  tests/TimeSeries/Price.test.ts
  tests/TimeSeries/Rating.test.ts
  tests/XRay/Breakdown.test.ts
  tests/version.test.ts
  tools/README.md
  tools/tests.ts
Labels: internal

#37 Fix dashboards missing in RNANews demo
  demos/dashboards-rna-news/demo.html
Labels: bugfix

#34 Added CLI command for API docs.
  .eslintrc
  package.json
  src/.eslintrc
  src/CLI/Library/APIServer.ts
  src/CLI/Library/APITemplate.ts
  src/CLI/Library/Database.ts
  src/CLI/Library/Server.ts
  src/CLI/Static/api.js
  src/CLI/Static/style.css
  src/CLI/connectors-morningstar.ts
  src/api.d.ts
  tools/api.ts
  tools/libs/TS.ts
Labels: enhancement

#38 Added RiskScoreConnector
  demos/dashboards-risk-score/demo.css
  demos/dashboards-risk-score/demo.html
  demos/dashboards-risk-score/demo.js
  demos/index.html
  docs/connectors/morningstar/risk-score/risk-score.md
  src/RiskScore/README.md
  src/RiskScore/RiskScoreConnector.ts
  src/RiskScore/RiskScoreConverter.ts
  src/RiskScore/RiskScoreJSON.ts
  src/RiskScore/RiskScoreOptions.ts
  src/RiskScore/index.ts
  src/Shared/MorningstarOptions.ts
  src/index.ts
  test/unit-tests/RiskScore/RiskScore.test.ts
Labels: enhancement

#39 Added metadata to RiskScoreConnector and improved demo
  demos/dashboards-risk-score/demo.css
  demos/dashboards-risk-score/demo.js
  docs/connectors/morningstar/risk-score/risk-score.md
  package-lock.json
  src/RiskScore/RiskScoreConnector.ts
  src/RiskScore/RiskScoreConverter.ts
  src/RiskScore/RiskScoreJSON.ts
  src/RiskScore/RiskScoreOptions.ts
  src/Shared/External.ts
  src/Shared/MorningstarOptions.ts
  tests/RiskScore/RiskScore.test.ts
Labels: enhancement

#31 Added GoalAnalysisConnector.
  docs/connectors/morningstar.md
  docs/connectors/morningstar/goal-analysis.md
  docs/connectors/morningstar/regulatory-news-announcements.md
  docs/connectors/morningstar/risk-score.md
  docs/connectors/morningstar/x-ray.md
  src/CLI/Library/APIServer.ts
  src/GoalAnalysis/GoalAnalysisConnector.ts
  src/GoalAnalysis/GoalAnalysisConverter.ts
  src/GoalAnalysis/GoalAnalysisJSON.ts
  src/GoalAnalysis/GoalAnalysisOptions.ts
  src/GoalAnalysis/index.ts
  src/api.d.ts
  src/index.ts
  tests/GoalAnalysis/GoalAnalysisConnector.test.ts
  tests/XRay/Breakdown.test.ts
  tools/api.ts
  tools/tests.ts
Labels: enhancement
